# INSTRUCTION ARG
FROM centos:7
RUN yum install httpd -y
COPY index.html /var/www/html/index.html
RUN chmod 777 /var/www/html
RUN chmod 666 /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-DFOREGROUND"]

